### ISSUE TITLE
能否出一个精简版本

### ISSUE THREAD

**Issue by liniu** [xiaoyuan-zs/vue-spyro-admin#1]
这个软件看起来很清爽，能否出一个精简版本，即只包括核心框架部份，类似[pure-admin-thin](https://github.com/pure-admin/pure-admin-thin)

**Comment by liniu** [comment]
认真研究了，本身还是很精简。

**Comment by Eddie-ZS** [comment]
最近一直在忙着写 pnpm + monorepo 多仓项目 忘了看邮箱信息了。 这个版本 我感觉很精简了。没有啥多的组件 都是比较常用的。



在 2024-10-28 11:58:16，"liniu" ***@***.***> 写道：

认真研究了，本身还是很精简。

**Comment by Eddie-ZS** [comment]
这个版本 是比较精简的 不需要的组件 你可以直接删掉即可



在 2024-10-24 14:57:32，"liniu" ***@***.***> 写道：

这个软件看起来很清爽，能否出一个精简版本，即只包括核心框架部份，类似pure-admin-thin

**Comment by Eddie-ZS** [comment]
后续会出一个 精简版本  只保留核心功能
